all:
  hosts:
    postgres-server:
      ansible_host: "{{ lookup('env', 'MY_POSTGRES_HOST_IP') }}"
      ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
      ansible_port: "{{ lookup('env', 'ANSIBLE_PORT') }}"
      ansible_ssh_private_key_file: "/tmp/ansible_ssh_key"
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
